# Generated by Django 4.2 on 2023-05-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfiguration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('openai_api_key', models.CharField(max_length=100)),
                ('facebook_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_api_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.TextField()),
                ('site_logo', models.TextField(blank=True, max_length=100, null=True)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_address', models.CharField(blank=True, max_length=200, null=True)),
                ('site_favicon', models.TextField(blank=True, max_length=100, null=True)),
                ('site_header_image', models.TextField(blank=True, max_length=100, null=True)),
                ('site_footer_text', models.TextField(blank=True, null=True)),
                ('site_twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('site_facebook_url', models.URLField(blank=True, null=True)),
                ('site_instagram_url', models.URLField(blank=True, null=True)),
                ('site_linkedin_url', models.URLField(blank=True, null=True)),
                ('site_youtube_url', models.URLField(blank=True, null=True)),
                ('enable_cache', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuration',
                'verbose_name_plural': 'historical configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('openai_api_key', models.CharField(max_length=100)),
                ('facebook_app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_app_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_api_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.TextField()),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('site_email', models.EmailField(max_length=254)),
                ('site_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('site_address', models.CharField(blank=True, max_length=200, null=True)),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('site_header_image', models.ImageField(blank=True, null=True, upload_to='header_images/')),
                ('site_footer_text', models.TextField(blank=True, null=True)),
                ('site_twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('site_facebook_url', models.URLField(blank=True, null=True)),
                ('site_instagram_url', models.URLField(blank=True, null=True)),
                ('site_linkedin_url', models.URLField(blank=True, null=True)),
                ('site_youtube_url', models.URLField(blank=True, null=True)),
                ('enable_cache', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=False)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
